version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  build:
  docker: # it uses the docker executor
      - image: circleci/node:13.8.0
  steps:
    - checkout
    - run: npm run lint
  test:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run test
  analyze:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run audit
workflows:
  welcome:
    jobs:
      - welcome/run
      - build
      - test
          requires:
            - build
      - analyze
          requires:
            - test
